CREATE TABLE USER
(
    id BIGINT(20)NOT NULL COMMENT 'Id',
    NAME VARCHAR(30)NULL DEFAULT NULL COMMENT 'Name',
    age INT(11)NULL DEFAULT NULL COMMENT 'Age',
    email VARCHAR(50)NULL DEFAULT NULL COMMENT 'Email',
    PRIMARY KEY (id)
);

